sudo: required
services:
  - docker

# before_install:
#   - docker build -t jeffvh/ptfiles-client-test -f ./client/Dockerfile.dev ./client

script:
  #   - docker run -e CI=true jeffvh/ptfiles-client-test npm test -- --coverage
  - echo "skipping tests"

after_success:
  - docker build -t jeffvh/ptfiles-client ./client
  - docker build -t jeffvh/ptfiles-nginx ./nginx
  - docker build -t jeffvh/ptfiles-api ./api
  # Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push jeffvh/ptfiles-client
  - docker push jeffvh/ptfiles-nginx
  - docker push jeffvh/ptfiles-api

deploy:
  edge: true
  provider: elasticbeanstalk
  region: ap-southeast-2
  app: ptfiles-docker
  env: PtfilesDocker-env
  bucket_name: elasticbeanstalk-ap-southeast-2-788408921554
  bucket_path: ptfiles-docker
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
