version: '3.4'

services:
  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - '3050:80'
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.local
    volumes:
      - ./client:/app
      - client_node_modules:/app/node_modules
    working_dir: /app
    # command: npm run start
    ports:
      - 3000:3000
    stdin_open: true
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 5555:5555
    # environment:
    #   - ConnectionStrings__RecauraDb=Server=sqlserver;Database=Recauradb;User=sa;Password=recApp123;
    depends_on:
      - sqlserver
  sqlserver:
    image: 'mcr.microsoft.com/mssql/server'
    environment:
      SA_PASSWORD: 'recApp123'
      ACCEPT_EULA: 'Y'

volumes:
  client_node_modules:
